// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace poc_voya_entity.Migrations
{
    [DbContext(typeof(cryptoContext))]
    [Migration("20221117125233_second")]
    partial class second
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("poc_voya_entity.Models.crypto", b =>
                {
                    b.Property<int>("cryptoID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("cryptoID"), 1L, 1);

                    b.Property<string>("cryptoDescription")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("cryptoName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("priceUSD")
                        .HasColumnType("float");

                    b.HasKey("cryptoID");

                    b.ToTable("crypto");
                });
#pragma warning restore 612, 618
        }
    }
}
